# Generated by Django 2.2.13 on 2020-06-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200629_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
