# Generated by Django 2.2.13 on 2020-06-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_customtext_boolean"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="char",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
