# Generated by Django 2.2.13 on 2020-06-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customtext_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
